# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Имя игры')),
                ('steps_number', models.IntegerField(verbose_name='Продолжительность игры')),
                ('current_step', models.IntegerField(default=1, verbose_name='Текущий шаг')),
                ('gamer_count', models.IntegerField(verbose_name='Количество играков')),
                ('total_fine', models.FloatField(default=0)),
                ('holding_cost', models.FloatField(default=0.5)),
                ('backorder_cost', models.FloatField(default=1)),
                ('demand_pattern', models.IntegerField(default=1)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_list', models.CharField(max_length=300, verbose_name='Список заказов')),
                ('supply_list', models.CharField(max_length=300, verbose_name='Список поставок')),
                ('storage', models.IntegerField()),
                ('current_order', models.IntegerField()),
                ('penalty', models.FloatField()),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custome', to='game.Gamer')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplie', to='game.Gamer')),
            ],
        ),
    ]
