# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='gamer',
            name='supplier',
        ),
        migrations.AddField(
            model_name='relationship',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='game.Gamer'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='gamer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to='game.Gamer'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='supplier',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='game.Gamer'),
        ),
    ]
