# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20160503_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='game.Gamer'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='game.Gamer'),
        ),
    ]
