# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20160503_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
