# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='is_step_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='current_order',
            field=models.IntegerField(default=6, verbose_name='Текущий заказ'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='order_list',
            field=models.CharField(default='[6]', max_length=300, verbose_name='Список заказов'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='penalty',
            field=models.FloatField(default=0, verbose_name='Штраф'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='storage',
            field=models.IntegerField(default=12, verbose_name='Склад'),
        ),
        migrations.AlterField(
            model_name='gamer',
            name='supply_list',
            field=models.CharField(default='[6]', max_length=300, verbose_name='Список поставок'),
        ),
    ]
