# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20160504_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(verbose_name='# хода')),
                ('current_order', models.IntegerField(verbose_name='Текущий заказ')),
                ('my_order', models.IntegerField(verbose_name='Мой заказ')),
                ('storage', models.IntegerField(verbose_name='Склад')),
                ('penalty', models.FloatField(verbose_name='Штраф')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Gamer')),
            ],
        ),
    ]
